version: 2.1

workflows:
  version: 2
  build-test:
    jobs:
      - rustfmt
      - audit
      - per-crate:
          name: mozsvc-common
          crate: mozsvc-common
      - per-crate:
          name: tracing-actix-web-mozlog
          crate: tracing-actix-web-mozlog
      - per-crate:
          name: actix-web-location
          crate: actix-web-location

jobs:
  per-crate:
    docker:
      - image: mozilla/cidockerbases:rust-latest
    parameters:
      crate:
        description: The crate to build and test. Passed to cargo with `-p`.
        type: string
    environment:
      RUST_BACKTRACE: 1
      CRATE: << parameters.crate >>
    steps:
      - checkout
      - run:
          name: Clippy
          command: cargo hack --each-feature clippy -p << parameters.crate >> -- -D warnings
      - run:
          name: Cargo build
          command: cargo hack --each-feature build -p << parameters.crate >>
      - run:
          name: Cargo test
          command: cargo hack --each-feature test -p << parameters.crate >> --verbose
      - run:
          name: Cargo Doc
          command: cargo doc -p << parameters.crate >> --all-features

  rustfmt:
    docker:
      - image: mozilla/cidockerbases:rust-latest
    steps:
      - checkout
      - run:
          name: Rustfmt
          command: cargo fmt --all -- --check

  audit:
    docker:
      - image: mozilla/cidockerbases:rust-latest
    steps:
      - checkout
      - run:
          name: Cargo audit
          command: cargo audit
