version: 2.1

workflows:
  version: 2
  build-test:
    jobs:
      - rustfmt
      - audit
      - per-crate:
          name: mozsvc-common
          crate: mozsvc-common
      - per-crate:
          name: tracing-actix-web-mozlog
          crate: tracing-actix-web-mozlog
      - per-crate:
          name: actix-web-location
          crate: actix-web-location

jobs:
  per-crate:
    docker:
      - image: rust:1
    parameters:
      crate:
        description: The crate to build and test. Passed to cargo with `-p`.
        type: string
    environment:
      RUST_BACKTRACE: 1
      CRATE: << parameters.crate >>
    steps:
      - checkout
      - run:
          name: Setup Rust
          command: |
            cargo install cargo-hack
            rustup component add clippy
      - run:
          name: Clippy
          command: cargo hack --feature-powerset clippy -p << parameters.crate >>
      - run:
          name: Cargo build
          command: cargo hack --feature-powerset build -p << parameters.crate >>
      - run:
          name: Cargo test
          command: cargo hack --feature-powerset test -p << parameters.crate >> --verbose
      - run:
          name: Cargo Doc
          command: cargo doc -p << parameters.crate >> --all-features

  rustfmt:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Setup Rust
          command: rustup component add rustfmt
      - run:
          name: Rustfmt
          command: cargo fmt --all -- --check

  audit:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Setup Rust
          command: cargo install cargo-audit
      - run:
          name: Cargo audit
          command: cargo audit
